# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ['main']

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    avoid_reduncy:
        runs-on: ubuntu-18.04
        steps:
            - name: Cancel Previous Redundant Builds
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ github.token }}

    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  # Make sure the actual branch is checked out when running on pull requests
                  ref: ${{ github.head_ref }}

            - name: Prettify code
              uses: creyD/prettier_action@v4.2
              with:
                  # This part is also where you can pass other options, for example:
                  prettier_options: --write **/*.{js,md}

    # Single deploy job since we're just deploying
    deploy:
        needs: [prettier]
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Pages
              uses: actions/configure-pages@v2
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  # Upload entire repository
                  path: '.'
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v1
